---
title: "DSO-530"
output: html_document
---

```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(tree)
```

```{r}
# read table
coupon = read.csv("coupon.csv")
data = read.csv("LocalArt.csv")

# join table
coupon$Coupon = "yes"
data = join(data, coupon[,-1], by = "CustID" )
data$Coupon = ifelse(is.na(data$Coupon),"no","yes")
#  no(3983)  yes(1017) 
```

```{r}
# do age
end = ymd("2015-12-31")
data$DOB = ymd(data$DOB)
data$Age = 2015 - year(data$DOB)

data = data %>%
    mutate(Age_cat = ifelse(Age <= 30, "younger",
                        ifelse(Age <=40, "middle-aged", 
                               "elder")))
ggplot(data , aes(Age, 
                  fill = Age_cat))+
    geom_bar()
```

```{r}
# do joindate
data$JoinDate = ymd(data$JoinDate)

data$Joindate_cat = ifelse(data$JoinDate<"2014-11-14","old","new")

ggplot(data,aes(JoinDate,
                fill = Joindate_cat)) +
    geom_bar(binwidth = 2)
```
```{r}
# do visits

data$Visits_freq = data$Visits / as.numeric((end-data$JoinDate )/30)

data$Visits_freq_cat = ifelse(data$Visits_freq<= 4,"low",
                         ifelse(data$Visits_freq<= 8,"medium","high"))


ggplot(data,aes(Visits_freq, 
                fill = Visits_freq_cat)) +
    geom_bar(stat = "count", binwidth = 0.2)
```

```{r}
# do revenue
data = data %>%
    filter(!is.na(1)) %>%
    mutate(Revenue = Paintings + Jewelry + Mosaics + Sculpture)

coupon1 = data %>%
    filter(Coupon == "yes")
coupon0 = data %>%
    filter(Coupon == "no")

write.csv(data,"cooldata.csv")
```

```{r}
ggplot(data, aes(Revenue,
                 fill = Coupon,
                 alpha = 0.5))+
    geom_density() +
    labs(title = "Revenue Density Distribution")

# t.test !!
t_revenue = t.test(coupon0$Revenue, coupon1$Revenue)
t_revenue$p.value
t_revenue$estimate
```