```{r}
library(tidyr)
library(stringr)

t_data = read.csv("t_table.csv")
t_data = t_data %>%
    filter(P_value<.001) %>%
    gather("Coupon_status","Est_mean",7:8) 

t_data$Coupon_status = str_sub(t_data$Coupon_status, start = 10)
```

```{r}
ggplot(t_data, aes(Art_type, Est_mean,
                   fill = Coupon_status)) +
    geom_bar(stat = "identity", position = "dodge")

# not obvious
```

```{r}
ggplot(t_data, aes(Art_type, Est_mean,
                   fill = Coupon_status)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_grid(Age_cat~Joindate_cat) +
    labs(title = "Coupon Effects on different Age & Joindate groups")
```

```{r}
ggplot(t_data, aes(Art_type, Est_mean,
                   fill = Coupon_status)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_grid(Age_cat ~ Visit_freq_cat) +
    labs(title = "Coupon Effects on different Age & Visit_frequency groups")
```

```{r}
ggplot(t_data, aes(Art_type, Est_mean,
                   fill = Coupon_status)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_grid(Joindate_cat~Visit_freq_cat) +
    labs(title = "Coupon Effects on different Joindate & Visit_frequency groups")
```
